// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSJi-xPkwgdr-DPa5r0B5TyLgWfym9ClQ',
    appId: '1:129126588106:web:b646fd0fe8a0e0bb441e33',
    messagingSenderId: '129126588106',
    projectId: 'note-nested',
    authDomain: 'note-nested.firebaseapp.com',
    storageBucket: 'note-nested.appspot.com',
    measurementId: 'G-NG2WPVDKS5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCC1mIig17UVoJ_GsEF-y9lKZlSXBRsNUI',
    appId: '1:129126588106:android:82f6267064f8743f441e33',
    messagingSenderId: '129126588106',
    projectId: 'note-nested',
    storageBucket: 'note-nested.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzaxkWZeJ_vD83ef7DDEOMJmEyoWMIZWM',
    appId: '1:129126588106:ios:8226a009a95bdec0441e33',
    messagingSenderId: '129126588106',
    projectId: 'note-nested',
    storageBucket: 'note-nested.appspot.com',
    iosBundleId: 'com.example.noteNested',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzaxkWZeJ_vD83ef7DDEOMJmEyoWMIZWM',
    appId: '1:129126588106:ios:ccbaacda555afa87441e33',
    messagingSenderId: '129126588106',
    projectId: 'note-nested',
    storageBucket: 'note-nested.appspot.com',
    iosBundleId: 'com.example.noteNested.RunnerTests',
  );
}
